[package]
name = "guess-the-number-in-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmath = "0.2.1"
rand = "0.8.5"

[[bin]]
name = "guess-the-number-in-rust"
path = "main.rs"
